strategies:
  - name: "GridStrategy_PNUT"
    enabled: true
    log_level: null
    exchange: "binance_huyan"
    class_path: "strategies.grid_strategy.GridStrategy"
    params:
      symbol: "PNUT/USDC:USDC"
      spacing: 0.0003
      order_value: 6
      grid_levels: 10
      leverage: 10
      health_check_interval_seconds: 180
      uniformity_threshold: 0.95
      max_price: 0.32
      min_price: 0.25
      close_positions_on_boundary: true

  - name: "FundingRateStrategy_HCR"
    enabled: true
    log_level: "INFO"
    exchange: "binance_hcr"
    class_path: "strategies.funding_rate_strategy.FundingRateStrategy"
    params:
      position_size_usd: 100.0
      rate_threshold: 0.0003
      open_offset_ms: 1000
      close_offset_ms: 50
      check_interval_seconds: 3480