binance:
  enabled: true  # 交易所启用开关
  accounts:
    binance_huyan:
      api_key: "ZivYkiT4w2oeMsLRHiLGKyVJor3exynZU9c4CnMvHwO9E185gBseMZzBgu8pwQUs"
      secret_key: "vqfmG7jDbxU59ejMdEU6cERNbhiz6lFXzDOIhLvx3bm8pNrXN9UAXP3qDePmzHle"
      enabled: true  # 账户启用开关
    binance_hcr:
      api_key: "X51FpIGrtEx0lujxdFXdiObHjRiBXic6fJgoOEcWQLNX03EJeULYatklxgAlzbN9"
      secret_key: "IOb8VtH7x5Vi04bBRjLBhPkuNDibMRm79r35OcZ9roVsmkfN8YMnov8L6sMReOKx"
      enabled: true  # 账户启用开关